### ISSUE TITLE
Errors on Linux Mint

### ISSUE THREAD

**Issue by ryanginn** [ryanginn/rtmp-player-python#2]
Currently having errors on Linux Mint, using Thonny and normal Python 3.

Console output:

```
>>> %Run what.py
Traceback (most recent call last):
  File "/home/ryan/what.py", line 6, in <module>
    from comtypes import CLSCTX_ALL
  File "/home/ryan/.local/lib/python3.10/site-packages/comtypes/__init__.py", line 207, in <module>
    _ole32 = oledll.ole32
NameError: name 'oledll' is not defined
>>> 
```

**Comment by ryanginn** [comment]
To be looked into
